language: node_js
node_js:
- '4.0'
- '4.1'
- '5.1'
sudo: required
install:
- npm install -g gulp
- npm install -g ts-node
- npm install
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run build.dev
  - npm run build.prod
services:
before_install:
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
notifications:
  email: true
after_failure: cat /home/travis/build/mgechev/angular2-seed/npm-debug.log
branches:
  only:
  - master
env:
- CXX=g++-4.8
