language: node_js
node_js:
- '4.0'
- '4.1'
- '5.1'
sudo: required
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
before_script:
  - npm install -g gulp
  - npm install -g ts-node
script:
  - npm run build.dev
  - npm run build.prod
services:
before_install:
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
notifications:
  email: true
after_failure: cat /home/travis/build/mgechev/angular2-seed/npm-debug.log
branches:
  only:
  - master
env:
  global:
  # https://github.com/DefinitelyTyped/tsd#tsdrc
  # Token has no scope (read-only access to public information)
  - TSD_GITHUB_TOKEN=9b18c72997769f3867ef2ec470e626d39661795d
